---
title: "Tour de France Game 2017"
output:
  html_document:
    self_contained: false
    includes:
      in_header: meta.html
      before_body: header.html
      after_body: footer.html
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

library(ggplot2)
library(knitr)
library(kableExtra)
library(DT)
library(reshape2)

options(knitr.table.format = "html")

setwd("C:/Users/davem/coding_2017/tourdefrance_game")
updated <- Sys.Date()

df_rider_name_results <- read.csv("rider-name-results.csv")
df_players_results <- read.csv("players-stage-results.csv")
df_player_st_winners <- read.csv("player-st-winners.csv")
player_totals_df <- read.csv("players-leaderboard.csv")
df_players_teams <- read.csv("players-teams.csv")
players_stage_accum <- read.csv("players-accum-stage-results.csv")
### ONLY INCLUDE BELOW FILE AT THE END OF TOUR FOR OVERALL FINISHING POINTS TABLE
df_rider_name_overall <- read.csv("rider_name_overall.csv")

m_players_accum <- melt(players_stage_accum, id.vars = "Players")
p1 <- ggplot(m_players_accum, aes(x = variable, y = value, group = Players)) +
  geom_line(aes(colour = Players), size = I(1.5)) +
  scale_colour_manual(values = c("#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7")) +
  theme(axis.text.x = element_text(angle = 60, hjust = 1)) +
  labs(x = "Stage", y = "Score", title = "Players acumulative scores after each stage")
```
<br>

### Stage results:

```{r, results="asis"}
datatable(df_rider_name_results,
          rownames = FALSE,
          options = list(pageLength = 5,
                         dom = 'ftp'))
# kable(df_rider_name_results) %>%
#   kable_styling(bootstrap_options = c("striper", "hover", "responsive"))
```
<br>
<!-- ONLY INCLUDE THIS CHUNCK AT THE END OF THE TOUR FOR FINISHING POINTS TABLE -->

### Final day rider points awards:

```{r, results="asis"}
kable(df_rider_name_overall) %>%
  kable_styling(position = "left", bootstrap_options = c("striped", "hover", "responsive"), full_width = F)
```
<br>

### Players stage winners:

```{r, out.width="50%", results="asis"}
datatable(df_player_st_winners,
          rownames = FALSE,
          options = list(pageLength = 5,
                         dom = 'tp'))
# kable(df_player_st_winners) %>%
#   kable_styling(position = "left", bootstrap_options = c("striper", "hover", "responsive"), full_width = F)
```
<br>

### Players stage scores:

```{r, results="asis"}
datatable(df_players_results,
          rownames = FALSE,
          options = list(scrollX = TRUE,
                         dom = 't'))
# kable(df_players_results) %>%
#   kable_styling(position = "left", bootstrap_options = c("striper", "hover", "responsive"), full_width = F)
```
<br>

### Leaderboard:

```{r, results="asis", fig.align = "center"}
kable(player_totals_df) %>%
  kable_styling(position = "left", bootstrap_options = c("striped", "hover", "responsive"), full_width = F)

plot(p1)
```
<br>

### Players teams:
#### Most popular rider: Tony Martin

```{r, results="asis"}
kable(df_players_teams) %>%
  kable_styling(bootstrap_options = c("striped", "hover", "responsive"))
```
<br>

[View how to play guide](http://www.bike2bytes.com/Tour-de-France-Game.php)
```{r, out.width = "100%"}
# datatable(df_player_st_winners, options = list(pageLength = 5, sDom  = '<"top">lrt<"bottom">ip'))
# 
# datatable(df_players_results, options = list(pageLength = 5, sDom  = '<"top">lrt<"bottom">ip'))
```

